title: Cloud Command
email: AbdullahOllivierre@gmail.com
description: >-
  A modern blog about cloud computing, automation, and DevOps practices.
baseurl: ""
url: "https://cloudcommand.org"
twitter_username: Ollivierre_A
github_username: aollivierre

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Comments settings
disqus:
  shortname: cloudcommand # Replace with your Disqus shortname

# Syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Header pages
header_pages:
  - about.md
  - categories/index.md
  - tags/index.md

# Social links
social_links:
  twitter: Ollivierre_A
  github: aollivierre
  linkedin: abdullah-ollivierre

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Abdullah Ollivierre
      comments: true # Enable comments by default
