title: Cloud Command
email: AbdullahOllivierre@gmail.com
description: >-
  A modern blog about cloud computing, automation, and DevOps practices.
baseurl: ""
url: "https://cloudcommand.org"
twitter_username: Ollivierre_A
github_username: aollivierre

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Additional settings
show_excerpts: true
header_pages:
  - about.md
  - projects.md

# Build settings
markdown: kramdown

# Header pages
header_pages:
  - about.md
  - categories/index.md
  - tags/index.md

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Abdullah Ollivierre
