version: '3'
services:
  jekyll:
    build: .
    volumes:
      - .:/site
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0
